### ISSUE TITLE
SSL Cert Problem

### ISSUE THREAD

**Issue by GregPlummer** [zentourist/viewpoint-spws#3]
I'm getting the following stack trace when trying to connect to a sharepoint site. Is there a way to specify a cacert file, or some other way to deal with certs? Thanks!

at depth 0 - 20: unable to get local issuer certificate
C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpclient-2.2.7/l
ib/httpclient/session.rb:300:in `connect': SSL_connect returned=1 errno=0 state=
SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLErr
or)
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient/session.rb:300:in`ssl_connect'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient/session.rb:757:in `block in connect'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:68:i
n`timeout'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:99:i
n `timeout'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient/session.rb:748:in`connect'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient/session.rb:606:in `query'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient/session.rb:161:in`query'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:1070:in `do_get_block'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:873:in`block in do_request'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:966:in `protect_keep_alive_disconnected'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:872:in`do_request'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:760:in `request'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httpc
lient-2.2.7/lib/httpclient.rb:663:in`get'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/connection.rb:31:in `get'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/connection.rb:24:in`authenticate'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/websvc/web_service_base.rb:36:in `initialize'

```
    from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
```

oint-spws-0.5.0/lib/viewpoint/spws/websvc/lists.rb:27:in `initialize'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/spws_client.rb:39:in`new'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/spws_client.rb:39:in `lists_ws'
        from C:/DevTools/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/viewp
oint-spws-0.5.0/lib/viewpoint/spws/spws_client.rb:69:in`get_lists'
        from SharepointServiceCall.rb:6:in `<main>'

**Comment by zentourist** [comment]
I need to iterate in viewpoint-spws a bit more for that functionality but I've been putting most of my time into Viewpoint development right now. You can get around your issue by 'lib/viewpoint/spws/connection.rb' where HTTPClient is instantiated and set `@httpcli.ssl_config.verify_mode = 0`

**Comment by GregPlummer** [comment]
Great, thank you Dan!
